apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: react-front 
    tier: front
  ports:
    - port: {{ .Values.service.port }} 
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
