apiVersion: v2
name: project
description: Helm chart for Kubernetes Demo
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
- name: "go-server"
  version: "0.1.0"
  repository: "@my-repo"
- name: "mysql-db"
  version: "0.1.0"
  repository: "@my-repo"
- name: "react-front"
  version: "0.1.0"
  repository: "@my-repo"
- name: "ecr-secret"
  version: "0.1.0"
  repository: "@my-repo"
icon: https://www.google.com/url?sa=i&url=https%3A%2F%2Fv2.helm.sh%2F&psig=AOvVaw2O1-BOZ4rEXXSdWgd2Azdf&ust=1706435527294000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCJj79O2l_YMDFQAAAAAdAAAAABAX
