apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: go-server
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }} 
    protocol: TCP
    name: http
