apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: {{ $.Values.default.app.destination.namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.api.host }} 
      http:
        paths:
          - path: {{ .Values.ingress.api.paths.auth.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.api.paths.auth.svcName }}
                port:
                  number: {{ .Values.ingress.api.paths.auth.svcPort }}
    - host: {{ .Values.ingress.front.host }}
      http:
        paths:
          - path: {{ .Values.ingress.front.paths.default.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.front.paths.default.svcName }}
                port:
                  number: {{ .Values.ingress.front.paths.default.svcPort }}
