{{- range $key,$val := .Values.projects }}
{{- $_ := set $ "curProjName" (print $.Values.envName "-" $key) }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ required "A valid envName is required" $.Values.envName }}-{{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
{{- if $val.clusterResourceWhitelist }}
  clusterResourceWhitelist:
{{ tpl $val.clusterResourceWhitelist $ | indent 4 }}
{{- end }}
  description: {{ $val.description }}
  sourceRepos:
{{ tpl $val.sourceRepos $ | indent 4 }}
{{- if $val.roles }}
  roles:
{{ tpl $val.roles $ | indent 4 }}
{{- end }}
  destinations:
    - server: {{ $.Values.default.app.destination.server }}
      namespace: {{ $.Values.default.app.destination.namespace }}
{{- end }}