kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-ecr-helper-role-full-access-to-secrets 
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["aws-ecr-regcred"]
  verbs: ["delete"] 
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]