apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
  namespace: {{ .Values.namespace }}
stringData:
  AWS_ACCESS_KEY_ID: {AWS_ACCESS_KEY_ID} 
  AWS_SECRET_ACCESS_KEY: {AWS_SECRET_ACCESS_KEY} 
  AWS_ACCOUNT: {AWS_ACCOUNT} 
